apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/dainmusty/minikube-project.git
    targetRevision: main
    path: bootstrap/        # ✅ ONLY Applications live here
    directory:
      recurse: true   # 👈 This allows argo to look into subdirectories

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
